version: '3'

services:
  kong_database:
    image: postgres:12.0-alpine
    networks:
      - kong_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpassword

  kong:
    image: kong
    networks:
      - kong_network
    ports:
      - "8000:8000/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
    environment:
      - KONG_PG_HOST=kong_database
      - KONG_PG_PASSWORD=kongpassword
      - KONG_DATABASE=off
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml

    command: sh -c "kong migrations bootstrap && kong start"
    volumes:
      - "./kong/config/:/usr/local/kong/declarative"

  taskgenie_auth_service:
    build: ./auth_service
    networks:
      - kong_network
    environment:
      NODE_ENV: dev
networks:
  kong_network:
    driver: bridge
    
